# Generated by Django 5.2.1 on 2025-05-23 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticketsbus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type1', models.CharField(choices=[('H2S', 'HowrahToSaltLake'), ('B2S', 'BidhannagarToSaltLake'), ('K2D', 'KolkataToDigha'), ('H2C', 'HowrahToCollegeStreet'), ('K2P', 'KolkataToPuri')], max_length=3)),
                ('type2', models.CharField(choices=[('GN', 'General Seat'), ('LD', 'Ladies Seat')], max_length=2)),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('departure_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_seats', models.PositiveIntegerField()),
            ],
        ),
    ]
