# Generated by Django 5.2.1 on 2025-05-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsbus',
            name='price',
            field=models.DecimalField(decimal_places=2, default=49.0, max_digits=10),
            preserve_default=False,
        ),
    ]
