# Generated by Django 5.2.1 on 2025-05-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_bus', '0002_ticketsbus_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsbus',
            name='type1',
            field=models.CharField(choices=[('GN', 'General Seat'), ('LD', 'Ladies Seat')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ticketsbus',
            name='type2',
            field=models.CharField(choices=[('GN', '1-25'), ('LD', '26-50')], max_length=3),
        ),
    ]
