# Generated by Django 5.2.1 on 2025-05-24 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticketsplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type1', models.CharField(choices=[('K2D', 'KolkataToDelhi'), ('D2M', 'DelhiToMumbai'), ('H2B', 'HyderabadToBangalore'), ('C2C', 'ChennaiToCoimbatore'), ('P2K', 'PuneToKolkata')], max_length=3)),
                ('type2', models.CharField(choices=[('BS', 'Business Class'), ('FR', 'First Class'), ('EC', 'Economy Class')], max_length=2)),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('departure_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_seats', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
