# Generated by Django 5.2.1 on 2025-05-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_plane', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsplane',
            name='type1',
            field=models.CharField(choices=[('K2D', 'KolkataToDelhi'), ('D2M', 'DelhiToMumbai'), ('H2B', 'HyderabadToBangalore'), ('C2U', 'ChennaiToUnitedStates'), ('P2K', 'PuneToKolkata')], max_length=3),
        ),
    ]
