# Generated by Django 5.2.1 on 2025-05-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_plane', '0002_alter_ticketsplane_type1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsplane',
            name='type1',
            field=models.CharField(choices=[('BS', 'Business Class'), ('FR', 'First Class'), ('EC', 'Economy Class')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ticketsplane',
            name='type2',
            field=models.CharField(choices=[('BS', '1-75'), ('FR', '76-190'), ('EC', '190-250+')], max_length=3),
        ),
    ]
