# Generated by Django 5.2.1 on 2025-05-19 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ] 

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('K2M', 'KolkataToMumbai'), ('K2C', 'KolkataToChennai'), ('K2D', 'KolkataToDelhi'), ('K2B', 'KolkataToBangalore'), ('K2H', 'KolkataToHydrabad')], max_length=3)),
            ],
        ),
    ]
