# Generated by Django 5.2.1 on 2025-05-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='type',
            field=models.CharField(choices=[('K2M', 'KolkataToMumbai'), ('C2K', 'ChennaiToKolkata'), ('K2D', 'KolkataToDelhi'), ('B2K', 'BangaloreToKolkata'), ('K2H', 'KolkataToHydrabad')], max_length=3),
        ),
    ]
