# Generated by Django 5.2.1 on 2025-05-22 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_tickets_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tickets',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tickets',
            name='destination',
            field=models.CharField(default='Kolkata', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='source',
            field=models.CharField(default='Kolkata', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='total_seats',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
