# Generated by Django 5.2.1 on 2025-05-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_tickets_arrival_time_tickets_departure_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='type',
            new_name='type1',
        ),
        migrations.AddField(
            model_name='tickets',
            name='type2',
            field=models.CharField(choices=[('BU', 'Business Class'), ('AC', 'AC Class'), ('SL', 'Sleeper Class')], default='Sleeper', max_length=2),
            preserve_default=False,
        ),
    ]
