# Generated by Django 5.2.1 on 2025-05-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_type_tickets_type1_tickets_type2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='price',
            field=models.DecimalField(decimal_places=2, default=999.0, max_digits=10),
            preserve_default=False,
        ),
    ]
