# Generated by Django 5.2.1 on 2025-05-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_tickets_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='type1',
            field=models.CharField(choices=[('BU', 'Business Class'), ('AC', 'AC Class'), ('SL', 'Sleeper Class')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='type2',
            field=models.CharField(choices=[('BU', '1-499'), ('AC', '500-999'), ('SL', '1000-1499')], max_length=3),
        ),
    ]
